spring:
    application:
        name: service-registry
        
eureka:
  instance: 
    hostname: nameless-bayou-22996.herokuapp.com
    nonSecurePort: 80
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
        defaultZone: https://nameless-bayou-22996.herokuapp.com/eureka/
    
