spring:
    application:
        name: service-registry
        
eureka:
  instance: 
    hostname: service-registry-y.herokuapp.com
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
        defaultZone: https://service-registry-y.herokuapp.com/eureka/
    
